# Secret para ambiente LOCAL
# Valores mock para desenvolvimento local (os serviços usam LocalStack)
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: feature-flags
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "local"
  AWS_SECRET_ACCESS_KEY: "local"
