# Secret para auth-service em ambiente LOCAL
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: feature-flags
type: Opaque
stringData:
  DATABASE_URL: "postgresql://auth_user:auth_password@postgres-auth.feature-flags.svc.cluster.local:5432/auth_db"
  MASTER_KEY: "12345"
---
# Secret para flag-service em ambiente LOCAL
apiVersion: v1
kind: Secret
metadata:
  name: flag-secret
  namespace: feature-flags
type: Opaque
stringData:
  DATABASE_URL: "postgresql://flags_user:flags_password@postgres-apps.feature-flags.svc.cluster.local:5432/flags_db"
  SERVICE_API_KEY: "tm_key_da04c214d888ea3f033e9f52038f7e99548c0e7052e0d4eaa9534e5aa8518b54"
---
# Secret para targeting-service em ambiente LOCAL
apiVersion: v1
kind: Secret
metadata:
  name: targeting-secret
  namespace: feature-flags
type: Opaque
stringData:
  DATABASE_URL: "postgresql://targeting_user:targeting_password@postgres-apps.feature-flags.svc.cluster.local:5432/targeting_db"
  SERVICE_API_KEY: "tm_key_da04c214d888ea3f033e9f52038f7e99548c0e7052e0d4eaa9534e5aa8518b54"
---
# Secret para evaluation-service em ambiente LOCAL
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: feature-flags
type: Opaque
stringData:
  REDIS_URL: "redis://redis.feature-flags.svc.cluster.local:6379"
  SERVICE_API_KEY: "tm_key_da04c214d888ea3f033e9f52038f7e99548c0e7052e0d4eaa9534e5aa8518b54"
