apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - analytics-service/deployment.yaml
  - analytics-service/service.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - evaluation-service/deployment.yaml
  - evaluation-service/service.yaml
  - flag-service/deployment.yaml
  - flag-service/service.yaml
  - targeting-service/deployment.yaml
  - targeting-service/service.yaml
